# Fastfile

# On force la plateforme iOS
platform :ios do
  
  desc "Builds the iOS application and exports the IPA"
  lane :build_ipa do
    # Cette étape compilera le projet Xcode
    build_app(
      # Ces valeurs sont basées sur la structure par défaut de Capacitor
      # Assurez-vous que le nom du workspace est correct (souvent 'App')
      workspace: "../ios/App.xcworkspace", 
      scheme: "App",                
      export_method: "ad-hoc",       # 'ad-hoc' pour les tests, ou 'development'
      
      # DÉFINITION DU CHEMIN DE SORTIE FIXE
      output_directory: "./build_output", # Le chemin est relatif au dossier 'android/'
      output_name: "arcadehub.ipa"    
    )
    
    # Si vous utilisez Match (Apple Code Signing) :
    # match(type: "development")
  end
end